<a href="https://colab.research.google.com/github/francescosalzano1/md5cracker/blob/master/LemmatizzazioneConNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [23]:
import numpy as np
import re

In [4]:
corpus=["Salavadanaio beve molto", "Paolo beve più di Salvadanaio", "Filippo è una cisterna", "Elio di Piero è una fabbrica di alcol", "Francesco beve il giusto"]


In [5]:
#definisco una funzione per eseguire la tokenizzazione su spazi

def corpus_tokenize(corpus):
  tokens=[re.split("\W+", sent.lower()) for sent in corpus]
  return tokens


In [6]:
corpus_tokens=corpus_tokenize(corpus)
print(corpus_tokens)

[['salavadanaio', 'beve', 'molto'], ['paolo', 'beve', 'più', 'di', 'salvadanaio'], ['filippo', 'è', 'una', 'cisterna'], ['elio', 'di', 'piero', 'è', 'una', 'fabbrica', 'di', 'alcol'], ['francesco', 'beve', 'il', 'giusto']]


In [22]:
def build_vocab(corpus_tokens):
  vocab=set({})

  for tokens in corpus_tokens:
    for token in tokens:
      vocab.add(token)

  return list(vocab)

index_to_word=build_vocab(corpus_tokens)
print(vocab)

['francesco', 'molto', 'cisterna', 'elio', 'giusto', 'fabbrica', 'una', 'beve', 'è', 'piero', 'più', 'paolo', 'filippo', 'il', 'salavadanaio', 'salvadanaio', 'alcol', 'di']


In [8]:
word_to_index= dict([word, i] for i, word in enumerate(index_to_word))
word_to_index["salvadanaio"]

15

In [9]:
docs_count= len(corpus)
print(docs_count)
# numero aprole nel vocabolario
vocab_size=len(index_to_word)
print(vocab_size)

5
18


In [10]:
#creo un'array di zeri
#passo numero  delle frasi nel copro come righe e il numero di parole del vocabolario come colonne
corpus_bow = numpy.zeros((docs_count,vocab_size))
#per vedere la dimensione di un array numpy
type(corpus_bow)
corpus_bow.shape

(5, 18)

In [11]:
#indicizzo tutti i token presenti in corpus_token che contiene la lista di token del corpo di testo
#la matrice corpus_bow è riempita di zeri cone zeros()che è una matrice numero delle frasi X numero di parole uniche di tutto il vocabolario 
#per ogni frase in corpus_tokens, per oni token nelle frasi di corpus_token aumeno di uno lo zero corrispondente a alla riga che identifica la frase e alla colonna data dall'indice del token
for i, tokens in enumerate(corpus_tokens):
  for token in tokens:
    corpus_bow[i][word_to_index[token]]+=1

corpus_bow

array([[0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
        0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        1., 2.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0.]])

In [12]:
#converto in funzione
def bag_of_words(corpus, return_vocab=False):
  corpus_tokens=corpus_tokenize(corpus)
   

  word_to_index= dict([word, i] for i, word in enumerate(index_to_word))

  docs_count= len(corpus)
# numero parole nel vocabolario
  vocab_size=len(index_to_word)

  corpus_bow = numpy.zeros((docs_count,vocab_size))
  for i, tokens in enumerate(corpus_tokens):
    for token in tokens:
     corpus_bow[i][word_to_index[token]]+=1

  if(return_vocab):
    return corpus_bow, index_to_word
  else:
    return corpus_bow




In [13]:
corpus_bow, vocab= bag_of_words(corpus, return_vocab=True)

print("Vocabolario:", vocab)

Vocabolario: ['francesco', 'molto', 'cisterna', 'elio', 'giusto', 'fabbrica', 'una', 'beve', 'è', 'piero', 'più', 'paolo', 'filippo', 'il', 'salavadanaio', 'salvadanaio', 'alcol', 'di']


In [14]:
# stampo ogni documento del corpo di testo con la sua rappresentazione bag of words
#zip fa eseguire ciclo in simultanea su due liste differenti
for sent, bow in zip(corpus, corpus_bow):
  print("Documento:", sent)
  print("BAG OF WORDS", bow)
  print("---------------")

Documento: Salavadanaio beve molto
BAG OF WORDS [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
---------------
Documento: Paolo beve più di Salvadanaio
BAG OF WORDS [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
---------------
Documento: Filippo è una cisterna
BAG OF WORDS [0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
---------------
Documento: Elio di Piero è una fabbrica di alcol
BAG OF WORDS [0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 2.]
---------------
Documento: Francesco beve il giusto
BAG OF WORDS [1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
---------------


In [ ]:
# Modello TD*IDF

In [29]:
corpus_tokens=corpus_tokenize(corpus)
index_to_word=build_vocab(corpus_tokens)
word_to_index=dict([word,i] for i, word in enumerate(index_to_word))

docs_count=len(corpus)
vocab_size=len(index_to_word)

In [33]:
#calcolo document frequency
#creo array vuto di dim = a quelle del vocabolario
df= np.zeros(vocab_size)


In [34]:
# iteriamo su indici e partole all'interno del vabolario
for i,word in enumerate(index_to_word):
  #iteriamo su ogni gruppo di token all'interno dei tokens del corpus, se la parola è presente nei token di un documento aumentiamo il contatore
  for tokens in corpus_tokens:
    if(word in tokens):
      df[i]+=1
    
index_to_word



['francesco',
 'molto',
 'cisterna',
 'elio',
 'giusto',
 'fabbrica',
 'una',
 'beve',
 'è',
 'piero',
 'più',
 'paolo',
 'filippo',
 'il',
 'salavadanaio',
 'salvadanaio',
 'alcol',
 'di']

In [35]:
##document
df

array([1., 1., 1., 1., 1., 1., 2., 3., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       2.])

In [36]:
#calcolo idf
idf=np.log(docs_count/df)+1
idf

array([2.60943791, 2.60943791, 2.60943791, 2.60943791, 2.60943791,
       2.60943791, 1.91629073, 1.51082562, 1.91629073, 2.60943791,
       2.60943791, 2.60943791, 2.60943791, 2.60943791, 2.60943791,
       2.60943791, 2.60943791, 1.91629073])

In [54]:
##calolo term frequency ci dice quante volte un termine appare in un documento
tf=np.zeros((docs_count, vocab_size))

In [60]:
#itero su indici e tokens di ogni documento, contiamo il numero di token sul docuemnto corrente,
# iteriamo su ogni token del doc corrente, ottengo l'indice del token corrente e aggiungo 1(tipo BOG) 
#alla fine divido il valore di ognli elemento per la lunghezza della lista del nunmero di parole che compongono il docuemnto
for i, tokens in enumerate(corpus_tokens):
  word_counts=len(tokens)
  for token in tokens:
    tf[i][word_to_index[token]]+=1
  tf[i]/=word_counts

tf

array([[0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33333333, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.2       , 0.        , 0.        ,
        0.2       , 0.2       , 0.        , 0.        , 0.        ,
        0.2       , 0.        , 0.2       ],
       [0.        , 0.        , 0.25      , 0.        , 0.        ,
        0.        , 0.25      , 0.        , 0.25      , 0.        ,
        0.        , 0.        , 0.25      , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.125     , 0.        ,
        0.125     , 0.125     , 0.        , 0.125     , 0.125     ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.125     , 0.25      ],
    

In [46]:
#calcolo tf*idf
tf_idf=df*idf
tf

array([[0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33333333, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.2       , 0.        , 0.        ,
        0.2       , 0.2       , 0.        , 0.        , 0.        ,
        0.2       , 0.        , 0.2       ],
       [0.        , 0.        , 0.25      , 0.        , 0.        ,
        0.        , 0.25      , 0.        , 0.25      , 0.        ,
        0.        , 0.        , 0.25      , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.125     , 0.        ,
        0.125     , 0.125     , 0.        , 0.125     , 0.125     ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.125     , 0.25      ],
    

In [50]:
#commenti e dettagli
idf.shape
tf.shape
#lo shape è dicerso! idf è un vettore lungo 18, tf è una matrice 5X18
#nel moemnto in cui facciamo tf*idf numopy esegue la moltiplicazione valore per valore. per ottenre la prima riga ogni elemento della prima riga della matrice viene moltiplicato con l'iesimo dell'array, stesso per la seconda riga da 1 a 18 esimo elemento

(5, 18)

In [64]:
##metto tutto in una funzionne
def np_tf_idf(corpus):
  
  corpus_tokens = corpus_tokenize(corpus)
  
  index_to_word = build_vocab(corpus_tokens)
  word_to_index = dict([(char, i) for i, char in enumerate(index_to_word)]) # creiamo il vocabolario inverso
  
  vocab_size = len(index_to_word)
  docs_count = len(corpus)
  
  # Document Frequency
    
  df = np.zeros(vocab_size)

  for i,word in enumerate(index_to_word):
    for tokens in corpus_tokens:
      if(word in tokens):
        df[i]+=1

  # Inverse Document frequency
        
  idf = np.log(docs_count/df)+1

  # Term Frequency
  
  tf = np.zeros((docs_count, vocab_size))
  
  for i, tokens in enumerate(corpus_tokens):
    word_counts = len(tokens)
    for token in tokens:
      tf[i][word_to_index[token]]+=1 # usiamo il vocabolario inverso
    tf[i]/=word_counts

  #TF-IDF
    
  tf_idf = tf*idf

  return tf_idf, index_to_word

    






In [65]:
corpus_tfidf, vocab = np_tf_idf(corpus)

print("Dizionario:",vocab)
print("\n")

for sent, tfidf in zip(corpus, corpus_tfidf):
  print("Frase:", sent)
  print("TF-IDF:", tfidf)
  print("-------")

Dizionario: ['francesco', 'molto', 'cisterna', 'elio', 'giusto', 'fabbrica', 'una', 'beve', 'è', 'piero', 'più', 'paolo', 'filippo', 'il', 'salavadanaio', 'salvadanaio', 'alcol', 'di']


Frase: Salavadanaio beve molto
TF-IDF: [0.         0.86981264 0.         0.         0.         0.
 0.         0.50360854 0.         0.         0.         0.
 0.         0.         0.86981264 0.         0.         0.        ]
-------
Frase: Paolo beve più di Salvadanaio
TF-IDF: [0.         0.         0.         0.         0.         0.
 0.         0.30216512 0.         0.         0.52188758 0.52188758
 0.         0.         0.         0.52188758 0.         0.38325815]
-------
Frase: Filippo è una cisterna
TF-IDF: [0.         0.         0.65235948 0.         0.         0.
 0.47907268 0.         0.47907268 0.         0.         0.
 0.65235948 0.         0.         0.         0.         0.        ]
-------
Frase: Elio di Piero è una fabbrica di alcol
TF-IDF: [0.         0.         0.         0.32617974 0. 